--@Autor(es): Mario Garrido, Vicente Romero
--@Fecha creación: 25/05/2019
--@Descripción: codigo DDL del caso de estudio donde se crean las tablas


CREATE TABLE MARCA(
    MARCA_ID NUMBER(10,0) CONSTRAINT MARCA_PK PRIMARY KEY,
    NOMBRE VARCHAR(60) NOT NULL UNIQUE,
    TELEFONO CHAR(10) NOT NULL,
);

CREATE TABLE ESTADO(
    ESTADO_ID NUMBER(10,0) CONSTRAINT ESTADO_PK PRIMARY KEY,
    CLAVE CHAR(4) NOT NULL UNIQUE,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHA(150) NOT NULL,
);

CREATE TABLE APARATO(
    APARATO_ID NUMBER(10,0) CONSTRAINT APARATO_PK PRIMARY KEY,
    NUMERO_SERIE CHAR(18) NOT NULL,
    NUMERO_MATRICULA CHAR(6) NOT NULL,
    CODIGO_ACCESO VARCHAR(32) NOT NULL,
    CAPACIDAD NUMBER(3,2) NOT NULL,
    PORCENTAJE_CARGA NUMBER(3,0) NOT NULL,
    ESTADO_ID NUMBER(10,0) NOT NULL,
    RECARGA_ID NUMBER(10,0) NOT NULL,
    MARCA_ID NUMBER(10,0) NOT NULL
);

CREATE TABLE ESTADO_HISTORICO(
    ESTADO_HISTORICO_ID NUMBER(10,0) CONSTRAINT ESTADO_HISTORICO_PK PRIMARY KEY,
    ESTADO_ID NUMBER(10,0) NOT NULL,
    FECHA_ESTADO DATE DEFAULT NOW(),
    APARATO_ID NUMBER(10,0) NOT NULL
);

CREATE TABLE ZONA(
    ZONA_ID NUMBER(10,0) CONSTRAINT ZONA_PK PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    VERTICES CLOB NOT NULL
);

CREATE TABLE ZONA_APARATO(
    ZONA_APARATO_ID NUMBER(10,0) CONSTRAINT ZONA_APARATO_PK PRIMARY KEY,
    ZONA_ID NUMBER(10,0) NOT NULL,
    APARATO_ID NUMBER(10,0) NOT NULL
);

CREATE TABLE UBICACION(
    UBICACION_ID NUMBER(10,0) CONSTRAINT UBICACION_PK PRIMARY KEY,
    LATITUD NUMBER(3,8) NOT NULL,
    LONGITUD NUMBER(3,8) NOT NULL,
    FECHA_HORA DATE NOT NULL DEFAULT SYSDATE,
    APARATO_ID NUMBER(10,0) NOT NULL
);

CREATE TABLE REEMPLAZO(
    REEMPLAZO_ID NUMBER(10,0) CONSTRAINT REEMPLAZO_PK PRIMARY KEY,
    APARATO_VIEJO NUMBER(10,0) NOT NULL,
    APARATO_NUEVO NUMBER(10,0) NOT NULL
);

CREATE TABLE USUARIO(
    USUARIO_ID NUMBER(10,0) CONSTRAINT USUARIO_PK PRIMARY KEY,
    EMAIL VARCHAR(60) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(60) NOT NULL,
    CONTRASEÑA CHAR(60) NOT NULL,
    PUNTOS NUMBER(10,0) NOT NULL
);

CREATE TABLE TARJETA(
    USUARIO_ID NUMBER(10,0) CONSTRAINT TARJETA_PK PRIMARY KEY,
    NUMERO CHAR(16) NOT NULL,
    AÑO_EXPIRACION CHAR(2) NOT NULL,
    MES_EXPIRACION CHAR(2) NOT NULL
);

CREATE TABLE TARJETA_PREPAGO(
    TARJETA_PREPAGO_ID NUMBER(10,0) CONSTRAINT TARJETA_PREPAGO_PK PRIMARY KEY,
    USUARIO_ID NUMERIC(10,0) NOT NULL,
    CODIGO_DE_BARRAS CHAR(21) NOT NULL,
    FECHA_REGISTRO DATE NOT NULL DEFAULT SYSDATE,
    FECHA_EXPIRACION DATE NOT NULL,
    IMPORTE NUMBER(16,2) NOT NULL
);

CREATE TABLE REPORTE(
    REPORTE_ID NUMBER(10,0) CONSTRAINT REPORTE_PK PRIMARY KEY,
    USUARIO_ID NUMBER(10,0) NOT NULL,
    APARATO_ID NUMBER(10,0) NOT NULL,
    FECHA DATE NOT NULL,
    LATITUD CHAR(10) NULL,
    LONGITUD CHAR(10) NULL,
    DESCRIPCION VARCHAR(200) NOT NULL
);

CREATE TABLE IMAGEN_REPORTE(
    IMAGEN_REPORTE_ID NUMBER(10,0) CONSTRAINT IMAGEN_REPORTE_PK PRIMARY KEY,
    REPORTE_ID NUMBER(10,0) NOT NULL,
    IMAGEN BLOB NOT NULL
);

CREATE TABLE SERVICIO(
    SERVICIO_ID NUMBER(10,0) CONSTRAINT SERVICIO_PK PRIMARY KEY,
    USUARIO_ID NUMBER(10,0) NOT NULL,
    TIPO CHAR(1) NOT NULL
);

CREATE TABLE RECARGA(
    SERVICIO_ID NUMBER(10,0) CONSTRAINT RECARGA_PK PRIMARY KEY,
    CLABE CHAR(18) NOT NULL,
    NOMBRE_BANCO VARCHAR(60) NOT NULL
);

CREATE TABLE VIAJE(
    SERVICIO_ID NUMBER(10,0) CONSTRAINT VIAJE_PK PRIMARY KEY,
    INICIO DATE NOT NULL,
    FIN DATE NOT NULL,
    FOLIO CHAR(13) NOT NULL,
    APARATO_ID NUMBER(10,0) NOT NULL,
    DURACION_VIAJE DATE GENERATED ALWAYS AS (FIN - INICIO) VIRTUAL
);

CREATE TABLE RENTA(
    SERVICIO_ID NUMBER(10,0) CONSTRAINT RENTA_PK PRIMARY KEY,
    INICIO DATE NOT NULL,
    DIAS_CUSTODIO NUMBER(10,0) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    APARATO_ID NUMBER(10,0) NOT NULL
);