--@Autor(es): Mario Garrido, Vicente Romero
--@Fecha creación: 25/05/2019
--@Descripción: codigo DDL del caso de estudio donde se crean las tablas


CREATE TABLE MARCA(
    MARCA_ID NUMBER(10,0) PRIMARY KEY,
    NOMBRE VARCHAR(60) NOT NULL,
    TELEFONO CHAR(10) NOT NULL
);

CREATE TABLE ESTADO(
    ESTADO_ID NUMBER(10,0) PRIMARY KEY,
    CLAVE CHAR(4) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHA(150) NOT NULL
;)

CREATE TABLE APARATO(
        APARATO_ID NUMBER(10,0) PRIMARY KEY,
        NUMERO_SERIE CHAR(18) NOT NULL,
        NUMERO_MATRICULA CHAR(6) NOT NULL,
        CODIGO_ACCESO VARCHAR(32) NOT NULL,
        CAPACIDAD NUMBER(3,2) NOT NULL,
        PORCENTAJE_CARGA NUMBER(3,0) NOT NULL,
        ESTADO_ID NUMBER(10,0) NOT NULL,
        RECARGA_ID NUMBER(10,0) NOT NULL,
        MARCA_ID NUMBER(10,0) NOT NULL
);

CREATE TABLE ESTADO_HISTORICO(
    ESTADO_HISTORICO_ID NUMBER(10,0) PRIMARY KEY,
    ESTADO_ID NUMBER(10,0) NOT NULL,
    FECHA_ESTADO DATE DEFAULT NOW(),
    APARATO_ID NUMBER(10,0) NOT NULL
);

CREATE TABLE ZONA(
    ZONA_ID NUMBER(10,0) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    VERTICES CLOB NOT NULL
);

CREATE TABLE ZONA_APARATO(
    ZONA_APARATO_ID NUMBER(10,0) PRIMARY KEY,
    ZONA_ID NUMBER(10,0) NOT NULL,
    APARATO_ID NUMBER(10,0) NOT NULL
);

CREATE TABLE UBICACION(
    UBICACION_ID NUMBER(10,0) PRIMARY KEY,
    LATITUD NUMBER(3,8) NOT NULL,
    LONGITUD NUMBER(3,8) NOT NULL,
    FECHA_HORA DATE NOT NULL DEFAULT NOW(),
    APARATO_ID NUMBER(10,0) NOT NULL
);

CREATE TABLE REEMPLAZO(
    REEMPLAZO_ID NUMBER(10,0) PRIMARY KEY,
    APARATO_VIEJO NUMBER(10,0) NOT NULL,
    APARATO_NUEVO NUMBER(10,0) NOT NULL
);

CREATE TABLE USUARIO(
    USUARIO_ID NUMBER(10,0) PRIMARY KEY,
    EMAIL VARCHAR()
)
