--@Autor(es): Mario Garrido, Vicente Romero
--@Fecha creación: 25/05/2019
--@Descripción: codigo DDL del caso de estudio donde se crean las tablas

CREATE SEQUENCE UBICACION_SEQ
    START WITH 33
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 33
;

CREATE SEQUENCE ZONA_SEQ
    START WITH 33
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 33
;

CREATE SEQUENCE ZONA_APARATO_SEQ
    START WITH 33
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 33
;

CREATE SEQUENCE UBICACION_SEQ
    START WITH 33
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 33
;

CREATE SEQUENCE MARCA_SEQ
    START WITH 33
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 33
;

CREATE SEQUENCE REEMPLAZO_SEQ
    START WITH 33
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 33
;

CREATE SEQUENCE APARATO_SEQ
    START WITH 33
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 33
;

CREATE SEQUENCE ESTADO_SEQ
    START WITH 33
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 33
;

CREATE SEQUENCE ESTADO_HISTORICO_SEQ
    START WITH 33
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 33
;

CREATE SEQUENCE REPORTE_SEQ
    START WITH 33
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 33
;

CREATE SEQUENCE USUARIO_SEQ
    START WITH 33
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 33
;

CREATE SEQUENCE IMAGEN_REPORTE_SEQ
    START WITH 33
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 33
;

CREATE SEQUENCE TARJETA_PREPAGO_SEQ
    START WITH 33
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 33
;
