--@Autor(es): Mario Garrido, Vicente Romero
--@Fecha creación: 25/05/2019
--@Descripción: Creacion de indices
CREATE UNIQUE INDEX ZONA_APARATO_ZONA_APARATO_ID_IUX ON ZONA_APARATO(ZONA_ID,APARATO_ID);
CREATE UNIQUE INDEX REEMPLAZO_APARATO_VIEJO_IUX ON REEMPLAZO(APARADO_VIEJO);
CREATE UNIQUE INDEX REEMPLAZO_APARATO_NUEVO_IUX ON REEMPLAZO(APARADO_NUEVO);
CREATE UNIQUE INDEX USUARIO_EMAIL_IUX ON USUARIO(LOWER(EMAIL));
CREATE UNIQUE INDEX TARJETA_NUMERO_IUX ON TARJETA(NUMERO);
CREATE UNIQUE INDEX TARJETA_PREPAGO_CODIGO_BARRAS_IUX ON TARJETA_PREPAGO(CODIGO_DE_BARRAS);
CREATE INDEX SERVICIO_USUARIO_ID_IX ON SERVICIO(USUARIO_ID);
CREATE INDEX VIAJE_APARATO_ID_IX ON VIAJE(APARATO_ID);
CREATE INDEX RENTA_APARATO_ID_IX ON RENTA(APARATO_ID);
CREATE INDEX UBICACION_APARATO_ID_IX ON UBICACION(APARATO_ID);
CREATE INDEX APARATO_NUMERO_MATRICULA_IX ON APARATO(UPPER(NUMERO_MATRICULA));
